#!/usr/bin/env bash

# set the context to ./app|./node directory, its not going to save anything there, this is becouse to make sure proper
# references are made to files if specified in Dockerfile
docker build -f app/Dockerfile -t ajando/app:latest ./app
docker build -f node/Dockerfile -t ajando/node:latest ./node
