version: 0.1
log:
  fields:
      service: registry
storage:
  s3:
    accesskey: xxx
    secretkey: xxx
    region: eu-central-1
    bucket: dmc-registry
    secure: true
    v4auth: true
  cache:
    blobdescriptor: inmemory
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
